name: rtcx_iot_smart
description: A Flutter plugin for RTCXIotSmart SDK integration
version: 1.0.0
homepage: https://example.com

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
#      android:
#        package: com.example.rtcx_iot_smart
#        pluginClass: RtcxIotSmartPlugin
      ios:
        pluginClass: RtcxIotSmartPlugin
